name: dft
version: 1.0.0-alpha.1
description: The specification for the Discourse Functional Transcription data format and transcription conventions
keywords:
  - linguistics
  - discourse
  - transcription
  - transcript
  - language
  - digital humanities
  - DFT
  - Discourse Functional Transcription
homepage: 'https://github.com/digitallinguistics/DFT'
bugs: 'https://github.com/digitallinguistics/DFT/issues'
license: See LICENSE.md
contributors:
  - name: John W. DuBois
  - name: Daniel W. Hieber
    url: 'https://danielhieber.com'
    email: dhieber@umail.ucsb.edu
  - name: Andrea L. Berez-Kroeker
repository:
  type: git
  url: https://github.com/digitallinguistics/DFT.git
private: true
